version: "3.8"

services: 
  service-registry:
    image: service-registry:latest
    build:
      context: ./service-registry
    ports:
      - "8761:8761"
    volumes:
      - service-registry-data:/var/service-registry
    networks: 
      - microservices-network

  api-gateway:
    image: api-gateway:latest
    build:
      context: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - service-registry
      - user-service
      - notification-service
      - event-service
      - statistics-service
      - turn-service
      - game-service
      - inventory-and-reward-service
    volumes:
      - api-gateway-data:/var/api-gateway
    networks: 
      - microservices-network

  user-service: 
    image: user-service:latest
    build:
      context: ./user-service
    ports: 
      - "8081:8081"
    depends_on:
      - service-registry
      - authdb
    environment: 
      - SPRING_DATASOURCE_URL=jdbc:postgresql://authdb:5432/authdb
      - SPRING_DATASOURCE_USERNAME=authuser
      - SPRING_DATASOURCE_PASSWORD=authpassword
    networks:  
      - microservices-network

  notification-service: 
    image: notification-service:latest
    build:
      context: ./notification-service
    ports: 
      - "8082:8082"
    depends_on:
      - service-registry
    volumes:
      - notification-service-data:/var/notification-service
    networks: 
      - microservices-network

  event-service: 
    image: event-service:latest
    build:
      context: ./event-service
    ports: 
      - "8083:8083"
    depends_on:
      - service-registry
      - eventdb
    environment: 
      - SPRING_DATASOURCE_URL=jdbc:postgresql://eventdb:5432/eventdb
      - SPRING_DATASOURCE_USERNAME=eventuser
      - SPRING_DATASOURCE_PASSWORD=eventpassword
    volumes:
      - event-service-data:/var/event-service
    networks: 
      - microservices-network

  statistics-service: 
    image: statistics-service:latest
    build:
      context: ./statistics-service
    ports: 
      - "8084:8084"
    depends_on:
      - service-registry
    volumes:
      - statistics-service-data:/var/statistics-service
    networks: 
      - microservices-network

  turn-service: 
    image: turn-service:latest
    build:
      context: ./turn-service
    ports: 
      - "8085:8085"
    depends_on:
      - service-registry
    volumes:
      - turn-service-data:/var/turn-service
    networks: 
      - microservices-network

  game-service: 
    image: game-service:latest
    build:
      context: ./game-service
    ports: 
      - "8086:8086"
    depends_on:
      - service-registry
      - gamedb
    environment: 
      - SPRING_DATASOURCE_URL=jdbc:postgresql://gamedb:5432/gamedb
      - SPRING_DATASOURCE_USERNAME=gameuser
      - SPRING_DATASOURCE_PASSWORD=gamepassword
    volumes:
      - game-service-data:/var/game-service
    networks: 
      - microservices-network

  inventory-and-reward-service: 
    image: inventory-and-reward-service:latest
    build:
      context: ./inventory-and-reward-service
    ports: 
      - "8087:8087"
    depends_on:
      - service-registry
      - inventory-and-reward-db
    environment: 
      - SPRING_DATASOURCE_URL=jdbc:postgresql://inventory-and-reward-db:5432/inventoryrewarddb
      - SPRING_DATASOURCE_USERNAME=inventoryuser
      - SPRING_DATASOURCE_PASSWORD=inventorypassword
    volumes:
      - inventory-and-reward-service-data:/var/inventory-and-reward-service
    networks: 
      - microservices-network

  authdb:
    image: postgres:13
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: authuser
      POSTGRES_PASSWORD: authpassword
    ports:
      - "5432:5432"
    volumes:
      - authdb-data:/var/lib/postgresql/data
    networks:
      - microservices-network

  eventdb:
    image: postgres:13
    environment:
      POSTGRES_DB: eventdb
      POSTGRES_USER: eventuser
      POSTGRES_PASSWORD: eventpassword
    ports:
      - "5433:5432"
    volumes:
      - eventdb-data:/var/lib/postgresql/data
    networks:
      - microservices-network

  gamedb:
    image: postgres:13
    environment:
      POSTGRES_DB: gamedb
      POSTGRES_USER: gameuser
      POSTGRES_PASSWORD: gamepassword
    ports:
      - "5434:5432"
    volumes:
      - gamedb-data:/var/lib/postgresql/data
    networks:
      - microservices-network

  inventory-and-reward-db:
    image: postgres:13
    environment:
      POSTGRES_DB: inventoryrewarddb
      POSTGRES_USER: inventoryuser
      POSTGRES_PASSWORD: inventorypassword
    ports:
      - "5435:5432"
    volumes:
      - inventory-and-reward-db-data:/var/lib/postgresql/data
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge

volumes:
  service-registry-data:
  api-gateway-data:
  user-service-data:
  notification-service-data:
  event-service-data:
  statistics-service-data:
  turn-service-data:
  game-service-data:
  inventory-and-reward-service-data:
  authdb-data:
  eventdb-data:
  gamedb-data:
  inventory-and-reward-db-data: