version: "1.0"
services:
  db:
    image: postgres:16.3-bullseye
    container_name: postgresVOU
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin@admin.io
      POSTGRES_PASSWORD: admin
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: elestio/pgadmin:latest
    container_name: pgadminVOU
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.io
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data: