# Stage 1: Build the application
FROM maven:3.9.8-eclipse-temurin-21 AS build
WORKDIR /api-gateway

# Copy the pom.xml and download dependencies
COPY pom.xml .
RUN mvn dependency:go-offline -B

# Copy the source code and build the application
COPY src ./src
RUN mvn clean install -DskipTests

# Check to list the JAR file (for debugging purposes)
RUN ls /api-gateway/target

# Start a new stage for the final image
FROM eclipse-temurin:21
WORKDIR /api-gateway

# Copy the JAR file from the build stage to the final image
COPY --from=build /api-gateway/target/api-gateway-*.jar api-gateway.jar

# Expose port 8761 to match the docker-compose settings
EXPOSE 8761

# Set the command to execute the JAR file
ENTRYPOINT ["java", "-jar", "api-gateway.jar"]
