# Use Eclipse Temurin JDK as the base image
FROM eclipse-temurin:21-jdk

# Set the working directory inside the container
WORKDIR /api-gateway

# Copy the JAR file from the build context into the container
COPY target/api-gateway-*.jar api-gateway.jar

# Expose port 8761 to match the docker-compose settings
EXPOSE 8761

# Set the command to execute the JAR file
ENTRYPOINT ["java", "-jar", "api-gateway.jar"]
