# Stage 1: Build the application
FROM maven:3.9.8-eclipse-temurin-17 AS build
WORKDIR /user-service

# Copy the pom.xml and download dependencies
COPY pom.xml .
RUN mvn dependency:go-offline -B

# Copy the source code and build the application
COPY src ./src
RUN mvn clean package -DskipTests

# Start a new stage for the final image
FROM eclipse-temurin:17
WORKDIR /user-service

# Copy the JAR file from the build stage to the final image
COPY --from=build /user-service/target/user-service-*.jar user-service.jar

# Expose port 8761 to match the docker-compose settings
EXPOSE 8082

# Set the command to execute the JAR file
ENTRYPOINT ["java", "-jar", "user-service.jar"]
