# Use Eclipse Temurin JDK as the base image
FROM eclipse-temurin:21-jdk

# Set the working directory inside the container
WORKDIR /user-service

# Copy the JAR file from the build context into the container
COPY target/user-service-*.jar user-service.jar

# Expose port 8761 to match the docker-compose settings
EXPOSE 8761

# Set the command to execute the JAR file
ENTRYPOINT ["java", "-jar", "user-service.jar"]
