# Stage 1: Build the application
FROM maven:3.9.8-eclipse-temurin-21 AS build
WORKDIR /streaming-service

# Copy the pom.xml and download dependencies
COPY pom.xml .
RUN mvn dependency:go-offline -B

# Copy the source code and build the application
COPY src ./src
RUN mvn clean install -DskipTests

# Check to list the JAR file (for debugging purposes)
RUN ls /streaming-service/target

# Start a new stage for the final image
FROM eclipse-temurin:21
WORKDIR /streaming-service

# Copy the JAR file from the build stage to the final image
COPY --from=build /streaming-service/target/streaming-service-*.jar streaming-service.jar

# Expose port 8761 to match the docker-compose settings
EXPOSE 8086
EXPOSE 8085

# Set the command to execute the JAR file
ENTRYPOINT ["java", "-jar", "streaming-service.jar"]
