# Stage 1: Build the application
FROM maven:3.9.8-eclipse-temurin-17 AS build
WORKDIR /streaming-service

# Copy the pom.xml and download dependencies
COPY pom.xml .
RUN mvn dependency:go-offline -B

# Copy the source code and build the application
COPY src ./src
RUN mvn clean package -DskipTests

# Stage 2: Create the final image
FROM eclipse-temurin:17
WORKDIR /streaming-service

# Set the timezone environment variable
ENV TZ=Asia/Ho_Chi_Minh

# Install tzdata package to handle timezone
RUN apt-get update && apt-get install -y tzdata && rm -rf /var/lib/apt/lists/*

# Copy the JAR file from the build stage to the final image
COPY --from=build /streaming-service/target/streaming-service-*.jar streaming-service.jar

# Expose ports to match the docker-compose settings
EXPOSE 8086
EXPOSE 8085

# Set the command to execute the JAR file
ENTRYPOINT ["java", "-jar", "streaming-service.jar"]