# Stage 1: Build the application
FROM maven:3.9.8-eclipse-temurin-17 AS build
WORKDIR /service-registry

# Copy the pom.xml and download dependencies
COPY pom.xml .
RUN mvn dependency:resolve-plugins

# Copy the source code and build the application
COPY src ./src
RUN mvn clean package -DskipTests

# Start a new stage for the final image
FROM eclipse-temurin:17
WORKDIR /service-registry

# Copy the JAR file from the build stage to the final image
COPY --from=build /service-registry/target/service-registry-*.jar service-registry.jar

# Expose port 8761 to match the docker-compose settings
EXPOSE 8761

# Set the command to execute the JAR file
ENTRYPOINT ["java", "-jar", "service-registry.jar"]
