# Stage 1: Build the application
FROM maven:3.9.8-eclipse-temurin-17 AS build
WORKDIR /inventory-and-reward-service

# Copy the pom.xml and download dependencies
COPY pom.xml .
RUN mvn dependency:go-offline -B

# Copy the source code and build the application
COPY src ./src
RUN mvn clean package -DskipTests

# Check to list the JAR file (for debugging purposes)
RUN ls /inventory-and-reward-service/target

# Start a new stage for the final image
FROM eclipse-temurin:17
WORKDIR /inventory-and-reward-service

# Copy the JAR file from the build stage to the final image
COPY --from=build /inventory-and-reward-service/target/inventory-and-reward-service-*.jar inventory-and-reward-service.jar

# Expose port 8761 to match the docker-compose settings
EXPOSE 8086

# Set the command to execute the JAR file
ENTRYPOINT ["java", "-jar", "inventory-and-reward-service.jar"]
